### ISSUE TITLE
Video don't open

### ISSUE THREAD

**Issue by mickymadfree** [MrKrabat/plugin.video.crunchyroll#1]
This is log: https://gist.github.com/mickymadfree/e759c3e75725f4616334e35cbeff579d
I try the various setting, but can't open the video. In the plugin https://github.com/Yoshiofthewire/CrunchyXBMC when I choose "adaptive" quality, same thing.

**Comment by MrKrabat** [comment]
Hi,
i uploaded an patch, it looks like the playback fallback did not start.

When the playback fails try to wait up to 30 seconds. A new loading-circle should appear.
Additionally i noticed that it can help to change the video quality from adaptive to 1080p.

The problem is that crunchyroll deliveres invalid stream files, but hopefully one of the two playback methods I implemented should work.

**Comment by mickymadfree** [comment]
Now it work, but only 1080p, no matter which quality to choose. Change quality in inputstream.adaptive has no effect. Is it crunchyroll problem? Because there is same thing https://github.com/Yoshiofthewire/CrunchyXBMC/issues/79.

**Comment by MrKrabat** [comment]
The settings in inputstream.adaptive will only change anything if you select adaptive as quality AND the playback with inputstream.adaptive works.

In case the fallback is used, Kodi will handle that and choose the best quality regarding to your internet connection.

If you want a lower resolution set it directly in the addon settings :)

**Comment by mickymadfree** [comment]
I set the quality in the addon setting (360p or 480p or 720p), but the video opens in 1080p.

**Comment by MrKrabat** [comment]
I see what you mean.
Crunchyroll removed the quality selection feature and are returning the adaptive-url for all quality settings.

That means it is currently impossible to set the quality for the fallback case.
[But it looks like it is possible](https://codedocs.xyz/AlwinEsch/kodi/group__python___player.html#ga3b0bab6df5632790bce08471c131353b)
