### ISSUE TITLE
Addon settings are being reset somehow.

### ISSUE THREAD

**Issue by earithramir** [MrKrabat/plugin.video.crunchyroll#13]
I've yet to find out when/how and why, but i've had serveral times that the addon suddenly asked me to loggin. When going to the addon settings everything is blank, also the settings.xml is black.
I'ts occurred enough for me to create a backup of the settings file to be able to copy that backup when it occurs again.
Im using a generated password, thus typing in that random string again and again takes time and is annoying.

**Comment by MrKrabat** [comment]
hmm I heard of several cases where people had a problem like your with other addons.
I would rather think that this issue is caused by another addon or your kodi installation.

The only thing I implemented is to wipe all session related details if the session could not be renewed. But this should definitely not affect your credentials
