### ISSUE TITLE
Some methods to choose the stream quality

### ISSUE THREAD

**Issue by mickymadfree** [MrKrabat/plugin.video.crunchyroll#3]
1. Set mpv as an external player and use youtube-dl to set the stream quality 
https://kodi.wiki/view/External_players
https://gist.github.com/mickymadfree/f0383b1719f61c134cc37ac0f3aaa082
This option for 360p: mpv --ytdl-raw-options=format=best[height=360]
Then right click on the anime siries > Play using > mpv360 / mpv480 / mpv720

2. Use youtube-dl or ffprobe to get the stream info from URL

**Comment by MrKrabat** [comment]
Hi,
I just got an idea how to choose the stream quality and it seems to work.

This is better than using an external player.
Give me some time to implement and test it :)

**Comment by mickymadfree** [comment]
Seems like these code decode URL, maybe it help you
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/crunchyroll.py

**Comment by MrKrabat** [comment]
This won't help.

1. There using the Crunchyroll website (which does not work reliable, because Crunchyroll uses Cloudflare) while my plugin is using the JSON API.
2. youtube-dl allows to download videos and subtitles, which is not allowed by Crunchyroll.

Anyway, quality selection works now with the latest patch.
